### ISSUE TITLE
[BUG] Internal server error: Failed to resolve import "tippy.js/dist/tippy.css" from "vue/src/main.js". Does the file exist?

### ISSUE THREAD

**Issue by swpfY** [SwanHubX/SwanLab#112]
## 🐛 Bug description [Please make everyone to understand it]

```bash
Error: The following dependencies are imported but could not be resolved:

  tippy.js/dist/tippy.css (imported by /Users/jqs/Desktop/Projects/BlackSwanXDU/SwanLab/vue/src/main.js)

Are they installed?
    at file:///Users/jqs/Desktop/Projects/BlackSwanXDU/SwanLab/node_modules/.pnpm/registry.npmmirror.com+vite@5.0.10_sass@1.69.6_terser@5.26.0/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:65148:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/jqs/Desktop/Projects/BlackSwanXDU/SwanLab/node_modules/.pnpm/registry.npmmirror.com+vite@5.0.10_sass@1.69.6_terser@5.26.0/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:64548:38
15:50:36 [vite] Pre-transform error: Failed to resolve import "tippy.js/dist/tippy.css" from "vue/src/main.js". Does the file exist?
15:50:37 [vite] Internal server error: Failed to resolve import "tippy.js/dist/tippy.css" from "vue/src/main.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/jqs/Desktop/Projects/BlackSwanXDU/SwanLab/vue/src/main.js:21:9
  19 |  // v-tippy
  20 |  import { directive } from 'vue-tippy'
  21 |  import 'tippy.js/dist/tippy.css'
     |          ^
  22 |  
  23 |  app.directive('tippy', directive)
```

## 🧑‍💻 Step to reproduce

```bash
pnpm install
```

## 👾 Expected result

[pnpm](https://pnpm.io/) is the best!

## 🚑 Any additional [like screenshots]

- **SwanLab Version**:

- **Platform**:

**Comment by SAKURA-CAT** [comment]
emmm it seems tippy.js 's problem...
