### ISSUE TITLE
[BUG] 在1个实验run起来但还没第1次log时，删除另外1个实验，后续的log都会报错

### ISSUE THREAD

**Issue by xiaolin199912** [SwanHubX/SwanLab#352]
## 🐛 Bug description [Please make everyone to understand it]

在一台工作站训练模型时，由于加载模型和数据集时间较长，所以第1次log在init之后的1分钟左右。
此时我在GUI删除另1个实验，则在当前时间产生第1次Log时，会报错，且后续的所有新实验Log都会报错。

报错：

```shell
Original exception was:
Traceback (most recent call last):
  File "/Users/zeyilin/Desktop/Coding/SwanLab测试/1.py", line 22, in <module>
    swanlab.log({"t/accuracy": acc, "loss": loss, "loss2": loss2})
  File "/Users/zeyilin/miniforge3/envs/test_py310/lib/python3.10/site-packages/swanlab/data/sdk.py", line 155, in log
    l = run.log(data, step, logger)
  File "/Users/zeyilin/miniforge3/envs/test_py310/lib/python3.10/site-packages/swanlab/data/run/main.py", line 486, in log
    self.__exp.add(key=key, data=d, step=step)
  File "/Users/zeyilin/miniforge3/envs/test_py310/lib/python3.10/site-packages/swanlab/data/run/exp.py", line 93, in add
    tag_obj.create_chart(tag, data)
  File "/Users/zeyilin/miniforge3/envs/test_py310/lib/python3.10/site-packages/swanlab/data/run/exp.py", line 308, in create_chart
    add_multi_chart(tag_id=tag.id, chart_id=self.__chart.id)
  File "/Users/zeyilin/miniforge3/envs/test_py310/lib/python3.10/site-packages/swanlab/db/utils/chart.py", line 186, in add_multi_chart
    if chart.sources.first().tag_id.type != tag.type:
AttributeError: 'NoneType' object has no attribute 'tag_id'

```

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.2.0

- **Platform**: MacOS

**Comment by SAKURA-CAT** [comment]
@Feudalman 你需要处理一下`chart.sources.first()`为None的情况
