### ISSUE TITLE
[BUG] Uncaught TypeError: Cannot read properties of null (reading 'change')

### ISSUE THREAD

**Issue by swpfY** [SwanHubX/SwanLab#434]
## 🐛 Bug description [Please make everyone to understand it]

```shell
Exception in callback H11Protocol.timeout_keep_alive_handler()
handle: <TimerHandle when=1604614.832140796 H11Protocol.timeout_keep_alive_handler()>
Traceback (most recent call last):
  File "/home/wangmengchao/miniconda3/envs/inpainting/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/wangmengchao/miniconda3/envs/inpainting/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 363, in timeout_keep_alive_handler
    self.conn.send(event)
  File "/home/wangmengchao/miniconda3/envs/inpainting/lib/python3.8/site-packages/h11/_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "/home/wangmengchao/miniconda3/envs/inpainting/lib/python3.8/site-packages/h11/_connection.py", line 537, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "/home/wangmengchao/miniconda3/envs/inpainting/lib/python3.8/site-packages/h11/_connection.py", line 272, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "/home/wangmengchao/miniconda3/envs/inpainting/lib/python3.8/site-packages/h11/_state.py", line 293, in process_event
    self._fire_event_triggered_transitions(role, _event_type)
  File "/home/wangmengchao/miniconda3/envs/inpainting/lib/python3.8/site-packages/h11/_state.py", line 311, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```

<img width="1467" alt="截屏2024-03-30 15 27 48" src="https://github.com/SwanHubX/SwanLab/assets/55043165/69e5bcb7-f773-45d2-8890-8f29731030cf">

## 🧑‍💻 Step to reproduce

1. Go to '....'

2. Click '....'

3. Something happened '....'

## 👾 Expected result

Write down the results you expect

## 🚑 Any additional [like screenshots]

- **SwanLab Version**:

- **Platform**:

**Comment by swpfY** [comment]
https://github.com/encode/httpx/issues/96

**Comment by SAKURA-CAT** [comment]
原因是数据量太大了，chart实例本身是异步生成的，但是数据量太大导致还没生成就调用了其他的api

**Comment by SAKURA-CAT** [comment]
此问题将在 #408 功能增加后得已修复
