### ISSUE TITLE
[BUG] 系统信息Json报错-TypeError: Object of type bytes is not JSON serializable

### ISSUE THREAD

**Issue by Zeyi-Lin** [SwanHubX/SwanLab#605]
## 🐛 Bug description [Please make everyone to understand it]

在算力容器中启动实验时，`swanlab.init`报错：

```txt
Traceback (most recent call last):                                                                  
  File "/home/hpc/projects/mnist/main.py", line 113, in <module>
    run = swanlab.init(
  File "/home/hpc/.local/lib/python3.10/site-packages/swanlab/data/sdk.py", line 191, in init
    run = register(
  File "/home/hpc/.local/lib/python3.10/site-packages/swanlab/data/run/__init__.py", line 15, in register
    run = SwanLabRun(*args, **kwargs)
  File "/home/hpc/.local/lib/python3.10/site-packages/swanlab/data/run/main.py", line 98, in __init__
    self.__exp: SwanLabExp = self.__register_exp(experiment_name, description, suffix, num=exp_num)
  File "/home/hpc/.local/lib/python3.10/site-packages/swanlab/data/run/main.py", line 288, in __register_exp
    self.__operator.before_init_experiment(self.__run_id, experiment_name, description, num, suffix, setter)
  File "/home/hpc/.local/lib/python3.10/site-packages/swanlab/data/run/operator.py", line 83, in before_init_experiment
    return self.__run_all(
  File "/home/hpc/.local/lib/python3.10/site-packages/swanlab/data/run/operator.py", line 52, in __run_all
    return {name: getattr(callback, method)(*args, **kwargs) for name, callback in self.callbacks.items()}
  File "/home/hpc/.local/lib/python3.10/site-packages/swanlab/data/run/operator.py", line 52, in <dictcomp>
    return {name: getattr(callback, method)(*args, **kwargs) for name, callback in self.callbacks.items()}
  File "/home/hpc/.local/lib/python3.10/site-packages/swanlab/data/callback_local.py", line 131, in before_init_experiment
    json.dump(get_system_info(self.settings), f)
  File "/usr/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

看get_system_info的结果为：

```txt
{'swanlab': {'version': '0.3.8', 'logdir': '/home/hpc/projects/swanlog'}, 'hostname': 'workspace-admin-pytorch1945', 'os': 'Linux-6.8.0-31-generic-x86_64-with-glibc2.35', 'python': '3.10.12', 'executable': '/bin/python', 'git_remote': None, 'cpu': 56, 'gpu': {'cores': 1, 'type': [b'Tesla P4'], 'memory': [8]}, 'git_info': (None, None), 'command': '/home/hpc/projects/mnist/main.py', 'memory': 126, 'cwd': '/home/hpc/projects'}
```

问题出在了gpu type出现了一个bytes，需要对system的json进行处理。

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: v0.3.8

- **Platform**: Linux

**Comment by pescn** [comment]
Check 了下，主要原因为pynvml.nvmlDeviceGetName返回值的类型的变化，容器云中使用的pynvml使用的版本为11.4.1，这时返回的数据为bytes；在11.5中返回的为str
