### ISSUE TITLE
[QUESTION] PadddleClas框架中使用Swanlab报错

### ISSUE THREAD

**Issue by wooyeonicon** [SwanHubX/SwanLab#637]
## 在PaddleClas框架中tools/train.py加入swanlab.init()报以下错误：
Call stack:
  File "tools/train.py", line 37, in <module>
    swanlab.init(
  File "C:\ProgramData\Anaconda3\lib\site-packages\swanlab\data\sdk.py", line 176, in init
    run = register(
  File "C:\ProgramData\Anaconda3\lib\site-packages\swanlab\data\run\__init__.py", line 15, in register
    run = SwanLabRun(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\swanlab\data\run\main.py", line 116, in __init__
    self.__operator.on_run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\swanlab\data\run\operator.py", line 97, in on_run
    return self.__run_all("on_run")
  File "C:\ProgramData\Anaconda3\lib\site-packages\swanlab\data\run\operator.py", line 54, in __run_all
    return {name: getattr(callback, method)(*args, **kwargs) for name, callback in self.callbacks.items()}
  File "C:\ProgramData\Anaconda3\lib\site-packages\swanlab\data\run\operator.py", line 54, in <dictcomp>
    return {name: getattr(callback, method)(*args, **kwargs) for name, callback in self.callbacks.items()}
  File "C:\ProgramData\Anaconda3\lib\site-packages\swanlab\data\callback_cloud.py", line 143, in on_run
    experiment_url = self._view_web_print()
  File "C:\ProgramData\Anaconda3\lib\site-packages\swanlab\data\callback_cloud.py", line 82, in _view_web_print
    swanlog.info("\U0001f3e0 View project at " + FONT.blue(FONT.underline(project_url)))
  File "C:\ProgramData\Anaconda3\lib\site-packages\swanlab\log\log.py", line 102, in wrapper
    can_write = func(self, message, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\swanlab\log\log.py", line 261, in info
    self.__logger.info(message)
Message: '\U0001f3e0 View project at \x1b[34m\x1b[4mhttps://swanlab.cn/@wooyeon/weed_classification\x1b[0m\x1b[0m'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f680' in position 26: illegal multibyte sequence

### 🚑 Any additional [like screenshots]

- **SwanLab Version**:  swanlab 0.3.11

- **Platform**: windows10+3090GPU+pytorch2.0.1+cu118+pycharm2019.2.6

**Comment by SAKURA-CAT** [comment]
fixed by #636

**Comment by SAKURA-CAT** [comment]
这是由于系统编码与实际不匹配造成的，您的系统编码应该是gbk，然后swanlab内置输出的了一些emoji表情

目前的策略是如果遇见UnicodeEncodeError不再输出到终端


感谢反馈！

**Comment by Zeyi-Lin** [comment]
新的v0.3.12发布后，您安装应该就可以work
