### ISSUE TITLE
[BUG] WSL 中获取NVIDIA显卡信息错误 AttributeError: 'SwanLabRun' object has no attribute 'monitor_cron'

### ISSUE THREAD

**Issue by funnythingfunnylove** [SwanHubX/SwanLab#753]
## 🐛 Bug description [Please make everyone to understand it]

在WSL 中使用pytorch 环境 出现获取硬件信息错误

## 🧑‍💻 Step to reproduce

swanlab: 👋 Hi JZ47321, welcome to swanlab!
swanlab: Syncing run ox-3 to the cloud
swanlab: 🌟 Run `swanlab watch /home/fl/gh/nanoGPT/swanlog` to view SwanLab Experiment Dashboard locally
swanlab: 🏠 View project at https://swanlab.cn/@JZ47321/my-awesome-project
swanlab: 🚀 View run at https://swanlab.cn/@JZ47321/my-awesome-project/runs/43hry0zksv8604ry16imt
swanlab: Error happened while training
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/swanlab/data/callback_cloud.py", line 202, in _except_handler
    get_run().finish(SwanLabRunState.CRASHED, error=self._traceback_error(tb, tp(val)))
TypeError: function takes exactly 5 arguments (1 given)

Original exception was:
Traceback (most recent call last):
  File "/home/fl/gh/nanoGPT/testlog.py", line 5, in <module>
    swanlab.init(
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/swanlab/data/sdk.py", line 163, in init
    run = register(
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/swanlab/data/run/__init__.py", line 15, in register
    run = SwanLabRun(*args, **kwargs)
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/swanlab/data/run/main.py", line 121, in __init__
    metadata, self.monitor_funcs = get_metadata(self.__settings.log_dir)
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/swanlab/data/run/metadata/__init__.py", line 21, in get_metadata
    hardware_info, monitor_funcs = get_hardware_info()
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/swanlab/data/run/metadata/hardware/__init__.py", line 26, in get_hardware_info
    nvidia = dec_hardware_func(get_nvidia_gpu_info, monitor_funcs)
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/swanlab/data/run/metadata/hardware/__init__.py", line 55, in dec_hardware_func
    x, y = func()
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/swanlab/data/run/metadata/hardware/gpu/nvidia.py", line 41, in get_nvidia_gpu_info
    gpu_name = pynvml.nvmlDeviceGetName(handle)  # types: bytes | str
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/pynvml.py", line 2182, in wrapper
    return res.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
swanlab: Experiment ox-3 has completed
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/swanlab/data/callback_cloud.py", line 193, in _clean_handler
    run.finish() if run.running else swanlog.debug("Duplicate finish, ignore it.")
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/swanlab/data/run/main.py", line 286, in finish
    getattr(run, "_SwanLabRun__cleanup")(error)
  File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/swanlab/data/run/main.py", line 205, in __cleanup
    if self.monitor_cron is not None:
AttributeError: 'SwanLabRun' object has no attribute 'monitor_cron'

## 👾 Expected result

Write down the results you expect

## 🚑 Any additional [like screenshots]

- **SwanLab Version**: 0.4.0 

- **Platform**: wsl ubuntu-24.04  conda python 3.9.19

**Comment by SAKURA-CAT** [comment]
以前出现过类似问题： https://github.com/SwanHubX/SwanLab/issues/605

新版本应该是忘记处理被删了

我解决一下

**Comment by SAKURA-CAT** [comment]
> File "/home/fl/miniconda3/envs/nanogpt/lib/python3.9/site-packages/pynvml.py", line 2182, in wrapper
> return res.decode()
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte

对了，方便看看您的pynvml是什么版本吗，根据错误日志来看似乎是内部错误
